# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ee7d796e9c9e037c23f4b4eb0c3530897ba053fe6c2937cd47098bdc553656ec33815ae5dce02667555a7466a1dea8033270415c813127abdb6bb2af916234e

test:
  secret_key_base: aacdc51412c609d2aa5fd035dbd88700d73c7cb45be1c7827eb555def28d3f77f49f1992c85d8aa027792157b18a823d9203f0753241d5162e6e39e19b9dd544

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
